#**Assignment For Numpy**
---









Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [ ]:
import numpy as np

2. Create a null vector of size 10 

In [ ]:
array=np.array([1,2,3,4,5,6,7,8,9,10])

3. Create a vector with values ranging from 10 to 49

In [3]:
import numpy as np
vec=np.arange(10,49)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [6]:
f=vec.shape
f

(39,)

5. Print the type of the previous array in question 3

In [7]:
type(vec)

numpy.ndarray

6. Print the numpy version and the configuration


In [4]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


8. Create a boolean array with all the True values

In [8]:
value=np.arange(10,50)
value>8

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

9. Create a two dimensional array




In [11]:
f=np.arange(8).reshape(2,4)
f

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

10. Create a three dimensional array



In [12]:
f=np.arange(12).reshape(3,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

12. Create a null vector of size 10 but the fifth value which is 1 

13. Create a 3x3 identity matrix

In [13]:
f=np.arange(9).reshape(3,3)
f

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [7]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5],dtype=float)
arr2=arr.astype(float)
arr2

array([1., 2., 3., 4., 5.])

15. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])  arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

---


Multiply arr1 with arr2


In [9]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1 * arr2


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [11]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
d=np.stack(arr1,arr2)
d

TypeError: _dstack_dispatcher() takes 1 positional argument but 2 were given

17. Extract all odd numbers from arr with values(0-9)

In [27]:
f=np.arange(-1,10,2)
f


array([-1,  1,  3,  5,  7,  9])

18. Replace all odd numbers to -1 from previous array

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [28]:
arr = np.arange(10)
arr

NameError: name 'arr' is not defined

20. Create a 2d array with 1 on the border and 0 inside

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

---

Replace the value 5 to 12

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

Minimun Value -3.13581542705388
Maximum Value 2.3334703479075793


26. Create a 10x10 array with random values and find the minimum and maximum values

In [11]:
f=np.random.randn((100)).reshape((10,10))
print(f"max value",{np.amax(f)})
print(f"main value",{np.amin(f)})

max value {1.614377959635121}
main value {-2.011851745563408}


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [14]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(f"Common Elements are : {np.intersect1d(a,b)}")

Common Elements are : [2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [15]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.searchsorted(a, np.intersect1d(a, b))
c

array([1, 5], dtype=int64)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [17]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
print(data[names != 'Will'])

[[ 0.23305775  0.0143032  -0.55011079  1.75626131]
 [-1.08334938 -0.47603822 -0.28432463  0.93803326]
 [-0.38089954 -0.99518103  0.19603247 -0.6843533 ]
 [ 0.18733465 -1.49092179  0.69105806  1.07806912]
 [-0.47316052  0.42058713 -0.2280444   0.60062477]
 [-0.87584072 -0.29278308  0.07392565 -2.58922256]
 [ 0.20016728 -0.27826728  1.05790883 -0.19743383]]
[[ 0.23305775  0.0143032  -0.55011079  1.75626131]
 [-1.08334938 -0.47603822 -0.28432463  0.93803326]
 [ 0.18733465 -1.49092179  0.69105806  1.07806912]
 [-0.87584072 -0.29278308  0.07392565 -2.58922256]
 [ 0.20016728 -0.27826728  1.05790883 -0.19743383]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [18]:
rand_arr = np.random.uniform(1,15, size=(5,3))
print(rand_arr)

[[ 5.18144978  8.05590094 11.25019123]
 [ 6.29436338  2.13747356 14.39923382]
 [ 1.84600417  2.23850459  5.01432721]
 [ 1.42735602  5.86441684  7.67418496]
 [ 6.53326688 12.25432733 14.44317813]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [20]:
f=np.arange(1,16).shape(2,4,4)
f

TypeError: 'tuple' object is not callable

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [19]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [20]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a, b)
c

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


40. Generate a matrix of 20 random values and find its cumulative sum

In [21]:
arr = np.random.uniform(1,20,size=(4,5))
arr = arr.astype('int32')
print(arr.cumsum())


[  3  18  19  36  53  59  64  81  95 111 114 125 142 158 175 176 194 201
 210 226]
